# Generated by Django 3.2.5 on 2024-01-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('episodes', models.IntegerField(max_length=100)),
                ('genre', models.ManyToManyField(related_name='anime', to='anime.Genre')),
            ],
        ),
    ]
